# Generated by Django 2.1 on 2020-05-04 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]
# DO NOT EVER DELETE A MIGRATION HERE SAME GOES FOR THE FILE
    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
